FROM	alpine:3.18 AS build

WORKDIR	/tmp/workdir

ARG	PREFIX="/tmp/install"

ARG	BUILD_PACKAGES=" \
	ca-certificates \
	curl \
	bzip2 \
	pkgconfig \
	coreutils \
	autoconf \
	automake \
	libtool \
	g++ \
	make \
	openjpeg-dev \
	libpng-dev \
	nasm \
	yasm \
	curl \
	libogg-dev \
	opus-dev \
	libvorbis-dev \
	lame-dev \
	cmake \
	zlib-dev \
	openssl-dev \
	boost-dev \
	libarchive-dev \
	libconfig-dev \
	taglib-dev \
	gtest-dev"

RUN	apk add --no-cache --update ${BUILD_PACKAGES}

# ffmpeg
ARG	FFMPEG_VERSION=4.3.5
RUN  \
	DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} && \
	curl -sLO https://ffmpeg.org/releases/ffmpeg-${FFMPEG_VERSION}.tar.bz2 && \
	tar -jx --strip-components=1 -f ffmpeg-${FFMPEG_VERSION}.tar.bz2

RUN \
	DIR=/tmp/ffmpeg && mkdir -p ${DIR} && cd ${DIR} && \
	./configure \
	--prefix=${PREFIX} \
	--disable-autodetect \
	--disable-debug \
	--disable-doc \
	--disable-ffplay \
	--disable-ffprobe \
	--disable-openssl \
	--disable-postproc \
	--disable-pixelutils \
	--disable-network \
	--enable-shared \
	--disable-static \
	--enable-gpl \
	--enable-small \
	--enable-version3 \
	--enable-nonfree \
	--enable-libmp3lame \
	--enable-libopenjpeg \
	--enable-libopus \
	--enable-libvorbis \
	--disable-everything \
	--enable-decoder=aac*,ac3*,alac,als,flac,mp3*,libopus,pcm*,libvorbis,wavpack,wma*,libopenjpg,png \
	--enable-encoder=libmp3lame,libopus,libvorbis \
	--enable-demuxer=aac,aiff,asf,flac,ipod,ogg,matroska,mov,mp3,mp4,wav,wv,webm \
	--enable-muxer=ogg,matroska,mp3,webm \
	--enable-protocol=file,pipe \
	--enable-filter=aresample \
	--extra-libs=-ldl && \
	make -j$(nproc) && \
	make install && \
	make distclean

# WT
ARG	WT_VERSION=4.10.0
RUN \
	DIR=/tmp/wt && mkdir -p ${DIR} && cd ${DIR} && \
	curl -sLO https://github.com/emweb/wt/archive/${WT_VERSION}.tar.gz && \
	tar -x --strip-components=1 -f ${WT_VERSION}.tar.gz

RUN \
	DIR=/tmp/wt && mkdir -p ${DIR} && cd ${DIR} && \
	cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${PREFIX} -DBUILD_EXAMPLES=OFF -DENABLE_LIBWTTEST=OFF -DCONNECTOR_FCGI=OFF && \
	make -j$(nproc) && \
	make install

# STB
ARG	STB_VERSION=5736b15f7ea0ffb08dd38af21067c314d6a3aae9
RUN \
	DIR=/tmp/stb && mkdir -p ${DIR} && cd ${DIR} && \
	curl -sLO https://github.com/nothings/stb/archive/${STB_VERSION}.tar.gz && \
	tar -x --strip-components=1 -f ${STB_VERSION}.tar.gz && \
	mkdir -p ${PREFIX}/include/stb && \
	cp ./*.h ${PREFIX}/include/stb

# LMS
COPY . /tmp/lms/
RUN \
	DIR=/tmp/lms/build && mkdir -p ${DIR} && cd ${DIR} && \
	PKG_CONFIG_PATH=/tmp/install/lib/pkgconfig CXXFLAGS="-I${PREFIX}/include" LDFLAGS="-L${PREFIX}/lib -Wl,--rpath-link=${PREFIX}/lib" cmake /tmp/lms/ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${PREFIX} -DCMAKE_PREFIX_PATH=${PREFIX} && \
	LD_LIBRARY_PATH=${PREFIX}/lib VERBOSE=1 make -j$(nproc) && \
	LD_LIBRARY_PATH=${PREFIX}/lib make test && \
	make install && \
	mkdir -p ${PREFIX}/etc/ && \
	cp /tmp/lms/conf/lms.conf ${PREFIX}/etc

# Now copy all the stuff installed in a new folder (/tmp/fakeroot/)
RUN \
	mkdir -p /tmp/fakeroot/bin && \
	for bin in ${PREFIX}/bin/ffmpeg ${PREFIX}/bin/lms*; \
	do \
		strip --strip-all $bin && \
		cp $bin /tmp/fakeroot/bin/; \
	done && \
	for lib in ${PREFIX}/lib/*.so; \
	do \
		strip --strip-all $lib; \
	done && \
	cp -r ${PREFIX}/lib /tmp/fakeroot/lib && \
	cp -r ${PREFIX}/share /tmp/fakeroot/share && \
	rm -rf /tmp/fakeroot/share/doc && \
	rm -rf /tmp/fakeroot/share/man

# Remove useless stuff
RUN \
	rm -rf /tmp/fakeroot/share/Wt/resources/jPlayer \
	rm -rf /tmp/fakeroot/share/Wt/resources/themes

## Release Stage
FROM		alpine:3.18 AS release
LABEL		maintainer="Emeric Poupon <itmfr@yahoo.fr>"

ARG	RUNTIME_PACKAGES=" \
	libssl3 \
	libcrypto3 \
	openjpeg \
	libpng \
	libogg \
	opus \
	libvorbis \
	lame-libs \
	zlib \
	boost-filesystem \
	boost-program_options \
	boost-system \
	boost-thread \
	libarchive \
	libconfig++ \
	taglib"

ARG	LMS_USER=lms
ARG	LMS_GROUP=lms

RUN	apk add --no-cache --update ${RUNTIME_PACKAGES}

RUN	addgroup -S ${LMS_GROUP} && \
	adduser -S -H ${LMS_USER} && \
	adduser ${LMS_USER} ${LMS_GROUP} && \
	mkdir -p /var/lms && chown -R ${LMS_USER}:${LMS_GROUP} /var/lms

VOLUME	/var/lms
VOLUME	/music
VOLUME	/usr/local/etc

USER	${LMS_USER}:${LMS_GROUP}

COPY	--from=build /tmp/fakeroot/ /usr
COPY	--from=build /tmp/fakeroot/share/lms/lms.conf /etc/lms.conf

EXPOSE	5082

ENTRYPOINT	["/usr/bin/lms"]

