# If already in cache, be silent
if(PSTREAMS_INCLUDE_DIRS)
  set (PSTREAMS_FIND_QUIETLY TRUE)
endif()

FIND_PATH(PSTREAMS_INCLUDE_DIR NAMES pstream.h
          PATH_SUFFIXES pstreams
          HINTS ${PSTREAMS_ROOT}/include $ENV{PSTREAMS_ROOT})

set(PSTREAMS_INCLUDE_DIRS ${PSTREAMS_INCLUDE_DIR})

# Handle the QUIETLY and REQUIRED arguments and set PSTREAMS_FOUND to TRUE if
# all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Pstreams DEFAULT_MSG PSTREAMS_INCLUDE_DIRS)

MARK_AS_ADVANCED(PSTREAMS_INCLUDE_DIRS)
